
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (./myapp) on
     Saturday, Jun 20, 2020 at 21:55:50
$ */

int add(int ,int );
int sub(int ,int );
int main();

static char *lance_static_t35 = "%d %d\n";

int add(int n1_2,int n2_3)
{
 int n3_5;
 int a_6;
 int b_7;
 int c_8;
 int t1;
 int t2;
 int t3;
 int t4;
 int t5;
 int t6;
 int t7;
 int t8;
 int t9;
 int t10;
 int t11;
 int t12;
 int t13;
 int t14;
 int t15;
 int t16;


 /* 4 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_5.c" */
 /* $ for(a = 0;a;a++){$ */

 LL1:

 /* 15 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_5.c" */
 /* $ n3 = n1 + n2;$ */

	t16 = n1_2 + n2_3;
	n3_5 = t16;

 /* 16 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_5.c" */
 /* $ return n3;$ */

	return n3_5;

}

int sub(int n1_9,int n2_10)
{
 int n3_12;
 int a_13;
 int b_14;
 int c_15;
 int t17;
 int t18;
 int t19;
 int t20;
 int t21;
 int t22;
 int t23;
 int t24;
 int t25;
 int t26;
 int t27;
 int t28;
 int t29;
 int t30;
 int t31;
 int t32;


 /* 22 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_5.c" */
 /* $ n3 = n1 - n2;$ */

	t17 = n1_9 - n2_10;
	n3_12 = t17;

 /* 24 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_5.c" */
 /* $ for(a = 0;a;a++){$ */

	if (t20) goto LL4;

 LL4:

 /* 35 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_5.c" */
 /* $ return n3;$ */

	return n3_12;

}

int main()
{
 int n1_17;
 int n2_18;
 int t33;
 int n3_19;
 int t34;
 int n4_20;
 int t36;


 /* 39 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_5.c" */
 /* $ int n1 = 10;$ */

	n1_17 = 10;

 /* 40 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_5.c" */
 /* $ int n2 = 15;$ */

	n2_18 = 15;

 /* 41 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_5.c" */
 /* $ int n3 = add(n1,n2);$ */

	t33 = add(n1_17,n2_18);

 /* 42 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_5.c" */
 /* $ int n4 = sub(n1,n2);$ */

	t34 = sub(n1_17,n2_18);

 /* 43 "/home/anushkini/Desktop/PD/plagtool/Test_lance/addSub_5.c" */
 /* $ printf("%d %d\n",n1,n2);$ */

	t36 = printf(lance_static_t35,n1_17,n2_18);

 /* 0 "???" */
 /* $ ???$ */

	return;

}
