
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (./myapp) on
     Saturday, Jun 20, 2020 at 21:38:29
$ */

int fib(int );
int main();

static char *lance_static_t18 = "%d\n";

int fib(int n_2)
{
 int a_4;
 int b_5;
 int c_6;
 int t1;
 int t2;
 int t3;
 int t6;
 int t7;
 int t8;
 int t9;
 int t10;
 int t11;
 int t4;
 int t5;


 /* 7 "/home/anushkini/Desktop/PD/plagtool/Test_lance/fib_3.c" */
 /* $ return n;$ */

	return n_2;


 /* 8 "/home/anushkini/Desktop/PD/plagtool/Test_lance/fib_3.c" */
 /* $ while(a<c){$ */

 LL2:

 /* 18 "/home/anushkini/Desktop/PD/plagtool/Test_lance/fib_3.c" */
 /* $ return fib(n-1) + fib(n-2);$ */

	t7 = n_2 - 1;
	t8 = fib(t7);
	t9 = n_2 - 2;
	t10 = fib(t9);
	t11 = t8 + t10;
	return t11;

}

int main()
{
 int p_8;
 int a_9;
 int t12;
 int q_10;
 int t13;
 int r_11;
 int t14;
 int b_12;
 int n_13;
 int c_14;
 int t15;
 int res_15;
 int t16;
 int t17;
 int t19;


 /* 28 "/home/anushkini/Desktop/PD/plagtool/Test_lance/fib_3.c" */
 /* $ int n = 10;$ */

	n_13 = 10;

 /* 30 "/home/anushkini/Desktop/PD/plagtool/Test_lance/fib_3.c" */
 /* $ int res = fib(n);$ */

	t15 = fib(n_13);
	res_15 = t15;

 /* 31 "/home/anushkini/Desktop/PD/plagtool/Test_lance/fib_3.c" */
 /* $ if(c != 10){$ */

	if (t17) goto LL5;

 LL5:

 /* 45 "/home/anushkini/Desktop/PD/plagtool/Test_lance/fib_3.c" */
 /* $ printf("%d\n",res);$ */

	t19 = printf(lance_static_t18,res_15);

 /* 0 "???" */
 /* $ ???$ */

	return;

}
