
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (./myapp) on
     Saturday, Jun 20, 2020 at 21:38:30
$ */

int main();

static char *lance_static_t4 = "The swapped numbers are %d and %d";

int main()
{
 int pq_3;
 int rs_4;
 int temp_5;
 int a_6;
 int b_7;
 int c_8;
 int t1;
 int t2;
 int t3;
 int t5;


 /* 2 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_2.c" */
 /* $ int pq = 3;$ */

	pq_3 = 3;

 /* 3 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_2.c" */
 /* $ int rs = 5;$ */

	rs_4 = 5;

 /* 10 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_2.c" */
 /* $ for(a = 0;a;a++){$ */

	if (t3) goto LL1;

 LL1:

 /* 18 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_2.c" */
 /* $ temp = pq;$ */

	temp_5 = pq_3;

 /* 19 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_2.c" */
 /* $ pq = rs;$ */

	pq_3 = rs_4;

 /* 20 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_2.c" */
 /* $ rs = temp;$ */

	rs_4 = temp_5;

 /* 26 "/home/anushkini/Desktop/PD/plagtool/Test_lance/s_2.c" */
 /* $ printf("The swapped numbers are %d and %d",pq,rs);$ */

	t5 = printf(lance_static_t4,pq_3,rs_4);

 /* 0 "???" */
 /* $ ???$ */

	return;

}
