
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (compile) on
     Sunday, Jun 21, 2020 at 12:59:22
$ */

int main();

static char *lance_static_t1 = "%d %d\n";

int main()
{
 int t2;
 int t3;


 /* 3 "./addSub-4.c" */
 /* $ printf("%d %d\n",25, -5);$ */

	t2 = -5;
	t3 = printf(lance_static_t1,25,t2);

 /* 0 "???" */
 /* $ ???$ */

	return;
}
