
/* 1 "LANCEV2" */
/* $
     IR file generated by LANCE V2.0 (stcleanup) on
     Wednesday, Jun 24, 2020 at 10:10:25
$ */

int add(int ,int );
int sub(int ,int );
int main();

static char *lance_static_t15 = "%d %d\n";

int add(int a_2,int b_3)
{
 int c_5;
 int t3;


 /* 10 "./Obf.c" */
 /* $ c = a + b ;$ */

	t3 = a_2 + b_3;
	c_5 = t3;

 /* 16 "./Obf.c" */
 /* $ return c ;$ */

	return c_5;

}

int sub(int a_9,int b_10)
{
 int c_12;
 int t8;


 /* 27 "./Obf.c" */
 /* $ c = a - b ;$ */

	t8 = a_9 - b_10;
	c_12 = t8;

 /* 33 "./Obf.c" */
 /* $ return c ;$ */

	return c_12;

}

int main()
{
 int a_17;
 int b_18;
 int t11;
 int c_19;
 int t12;
 int d_20;
 int t16;


 /* 37 "./Obf.c" */
 /* $ int a = 10;$ */

	a_17 = 10;

 /* 38 "./Obf.c" */
 /* $ int b = 15;$ */

	b_18 = 15;

 /* 39 "./Obf.c" */
 /* $ int c = add(a,b);$ */

	t11 = add(a_17,b_18);
	c_19 = t11;

 /* 40 "./Obf.c" */
 /* $ int d = sub(a,b);$ */

	t12 = sub(a_17,b_18);
	d_20 = t12;

 /* 47 "./Obf.c" */
 /* $ printf("%d %d\n",c,d);$ */

	t16 = printf(lance_static_t15,c_19,d_20);

 /* 0 "???" */
 /* $ ???$ */

	return;

}
